project:
  type: website
  output-dir: docs

website:

  navbar:
    # title: "<img src='img/logo.png' alt='Logo' class='logo'>"
    background: "white"
    foreground: "#a7a9ac"
    
    
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/sofiazorrilla/data.table_long/blob/main/README.md
            
  sidebar:
    style: "floating"
    foreground: "#a7a9ac"
    search: true
    alignment: right
    contents:
      - section: "Introducción"
        contents:
          - index.qmd
          - tema1.qmd
          - tema2.qmd
      - section: "Operaciones"
        contents:
          - tema3.qmd
          - tema4.qmd
          - tema5.qmd
          - tema7.qmd
          - tema8.qmd
          - tema9.qmd
          - tema6.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    code-wrap: true
    code-overflow: wrap
    page-layout: full
    code-block-style: "line-wrap"
    grid: 
      body-width: 1100px
      sidebar-width: 250px
      margin-width: 150px
      gutter-width: 0.8em
  
engine: knitr
knitr:
  opts_chunk: 
    R.options:
      width: 120
